on:
  workflow_dispatch:  #manual execution
  push:               #automatic execution
    branches: 
      - main

#env:
#  SERVICE: consumer


#dockerfile que pongo en el manage.py runserver?
#error en los unit test?


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set enviroment
        id: enviroment
        run: |
          echo "This is build job"
      
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.0 
      
      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Database Migration
        run: |
          python manage.py makemigrations
          python manage.py migrate


# Unit testing using PyTest        
  unit_test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set enviroment
        id: enviroment
        run: |
           echo "This is unit_test job"
      
      - name: Checkout
        uses: actions/checkout@v4
      
      #### DEBUG 
      #- name : /home/runner/work/devsu/devsu
      #  run : "ls /home/runner/work/devsu/devsu"
      #- name : machine ls $GITHUB_WORKSPACE
      #  run : "ls -la $GITHUB_WORKSPACE"
      #- name : machine ls $HOME
      #  working-directory : "."
      #  run : "ls -la $HOME"
      #### DEBUG 

      #option 1
      #- name: Test with pytest
      #  run: |
      #    pip install pytest pytest-cov
      #    pytest ./api/tests.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html 

      #option 2
      # Install pip and pytest
     # - name: Install dependencies
     #   run: |
     #     python -m pip install --upgrade pip
     #     pip install pytest pytest-cov
     # - name: Test with pytest
     #   #run: pytest tests.py --doctest-modules --junitxml=junit/test-results.xml
     #   run: pytest ./home/runner/work/devsu/devsu/api/tests.py --doctest-modules --junitxml=junit/test-results.xml
     # - name: Upload pytest test results
     #   uses: actions/upload-artifact@v3
     #   with:
     #     name: pytest-results
     #     path: junit/test-results.xml
      # Use always() to always run this step to publish test results when there are test failures
     #   if: ${{ always() }}
           

# Static Code Analysis using Ruff
  static_code_analysis:
    needs: unit_test
    runs-on: ubuntu-latest
    steps:
      - name: Set enviroment
        id: enviroment
        run: |
           echo "This is static_code_analysis job"
      
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint with Ruff
        run: |
          pip install ruff
          ruff check --fix .
        continue-on-error: true       #if detects an error and cannot fix it, then the pipeline should continue so it's not aborted  


# Code Coverage Analaysis using PyTest-Cov
  code_coverage:
    needs: static_code_analysis
    runs-on: ubuntu-latest
    steps:
      - name: Set enviroment
        id: enviroment
        run: |
           echo "This is code_coverage"       
    # aca puedo usar el coverage del pytest


# Vulnerabilities Scan using CodeQL
  vulnerability_scan: 
    needs: code_coverage
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
          
    steps:
      - name: Set enviroment
        id: enviroment
        run: |
           echo "This is vulnerability_scan job"         

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ];
          then pip install -r requirements.txt;
          fi
          echo "CODEQL_PYTHON=$(which python)" >> $GITHUB_ENV

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: python
          setup-python-dependencies: false    # override default behavior to avoid installing Python dependencies
           

# Build Docker image and push it to Docker Hub
  docker_build_push:
    needs: vulnerability_scan
    runs-on: ubuntu-latest
    steps:
      - name: Set enviroment
        id: enviroment
        run: |
           echo "This is docker_build_push job" 
      
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}  
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: jolivieridocker/devsu:latest