on:
  workflow_dispatch:  #manual execution
  push:               #automatic execution
    branches: 
      - main

#env:
#  SERVICE: consumer

jobs:
  code_build:
    runs-on: ubuntu-latest
    steps:
      - name: Set enviroment
        id: enviroment
        run: |
          echo "This is code_build job"
      
      - name: Checkout
        uses: actions/checkout@v4

  unit_test:
    needs: code_build
    runs-on: ubuntu-latest
    steps:
      - name : /home/runner/work/devsu/devsu
        run : "ls /home/runner/work/devsu/devsu"
      - name : machine ls $HOME
        working-directory : "."
        run : "ls -la $HOME"
      
      - name: Set enviroment
        id: enviroment
        run: |
           echo "This is unit_test"
      #- name: Test with pytest
      #  run: |
      #    pip install pytest pytest-cov
      #    pytest tests.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html 

      # Install pip and pytest
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Test with pytest
        #run: pytest tests.py --doctest-modules --junitxml=junit/test-results.xml
        run: pytest ./home/runner/work/devsu/devsu/api/tests.py --doctest-modules --junitxml=junit/test-results.xml
      - name: Upload pytest test results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results
          path: junit/test-results.xml
      # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
           

  static_code_analysis:
    needs: unit_test
    runs-on: ubuntu-latest
    steps:
      - name: Set enviroment
        id: enviroment
        run: |
           echo "This is static_code_analysis"

      - name: Lint with Ruff
        run: |
          pip install ruff
          ruff --output-format=github .
        continue-on-error: true                    

  code_coverage:
    needs: static_code_analysis
    runs-on: ubuntu-latest
    steps:
      - name: Set enviroment
        id: enviroment
        run: |
           echo "This is code_coverage"       

  docker_build_push:
    needs: code_coverage
    runs-on: ubuntu-latest
    steps:
      - name: Set enviroment
        id: enviroment
        run: |
           echo "This is docker_build_push" 

      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

     #     - name: Build, tag, and push image to Amazon ECR
     #     id: build-image
     #     env:
      
     #     run: |
     #       docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
     #       docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
     #       docker push -a $ECR_REGISTRY/$ECR_REPOSITORY
     #       echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT          

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: jolivieridocker/devsu:latest

  vulnerability_scan:  #optional
    runs-on: ubuntu-latest
    steps:
      - name: Set enviroment
        id: enviroment
        run: |
           echo "This is vulnerability_scan"   
 
  deploy_docker_k8s:  #check
    runs-on: ubuntu-latest
    steps:
      - name: Set enviroment
        id: enviroment
        run: |
           echo "This is deploy_docker_k8s"            
           

    #  - name: Build, tag, and push image to Amazon ECR
    #    id: build-image
    
    #    run: |
    #      docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
    #      docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
    #      docker push -a $ECR_REGISTRY/$ECR_REPOSITORY
    #      echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
  
          
